apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-applicationsets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YadinDeri/gitops-multiapps-deploy.git
    targetRevision: HEAD
    path: applicationsets
    # directory:
    #   recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true