apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # - app: nginx
          - app: jenkins
          # - app: nginxx
  template:
    metadata:
      name: '{{app}}-dev'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/YadinDeri/gitops-multiapps-deploy.git'
        targetRevision: HEAD
        path: 'base/{{app}}'
        # path: 'base/nginx'
        helm:
          valueFiles:
            - '../../apps/dev/{{app}}-values.yaml'
            # - '../../apps/dev/nginx-values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true