apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app1
  labels:
    app: {{ .Release.Name }}-app1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-app1